INSERT INTO SymptomNames (sName) VALUES ('palpitations');
INSERT INTO SymptomNames (sName) VALUES ('chills');
INSERT INTO SymptomNames (sName) VALUES ('clammy skin');
INSERT INTO SymptomNames (sName) VALUES ('cloudy urine');
INSERT INTO SymptomNames (sName) VALUES ('cold sweat');
INSERT INTO SymptomNames (sName) VALUES ('conjunctivitis');
INSERT INTO SymptomNames (sName) VALUES ('cough');
INSERT INTO SymptomNames (sName) VALUES ('dry cough');
INSERT INTO SymptomNames (sName) VALUES ('productive cough');
INSERT INTO SymptomNames (sName) VALUES ('hemoptysis');
INSERT INTO SymptomNames (sName) VALUES ('dehydration');
INSERT INTO SymptomNames (sName) VALUES ('dizziness');
INSERT INTO SymptomNames (sName) VALUES ('dysuria');
INSERT INTO SymptomNames (sName) VALUES ('tachypnea');
INSERT INTO SymptomNames (sName) VALUES ('fatigue');
INSERT INTO SymptomNames (sName) VALUES ('fever');
INSERT INTO SymptomNames (sName) VALUES ('hematuria');
INSERT INTO SymptomNames (sName) VALUES ('hypotension');
INSERT INTO SymptomNames (sName) VALUES ('dyspepsia');
INSERT INTO SymptomNames (sName) VALUES ('presyncope');
INSERT INTO SymptomNames (sName) VALUES ('syncope');
INSERT INTO SymptomNames (sName) VALUES ('malaise');
INSERT INTO SymptomNames (sName) VALUES ('rhinitis');
INSERT INTO SymptomNames (sName) VALUES ('nausea');
INSERT INTO SymptomNames (sName) VALUES ('rhinorrhea');
INSERT INTO SymptomNames (sName) VALUES ('sense of incomplete bladder emptying');
INSERT INTO SymptomNames (sName) VALUES ('dyspnea');
INSERT INTO SymptomNames (sName) VALUES ('smelly urine');
INSERT INTO SymptomNames (sName) VALUES ('sneezing');
INSERT INTO SymptomNames (sName) VALUES ('diaphoresis');
INSERT INTO SymptomNames (sName) VALUES ('tachycardia');
INSERT INTO SymptomNames (sName) VALUES ('polyuria');
INSERT INTO SymptomNames (sName) VALUES ('vomiting');
INSERT INTO SymptomNames (sName) VALUES ('dysphagia');
INSERT INTO SymptomNames (sName) VALUES ('ataxia');
INSERT INTO SymptomNames (sName) VALUES ('bradykinesia');
INSERT INTO SymptomNames (sName) VALUES ('impotence');
INSERT INTO SymptomNames (sName) VALUES ('bradypnea');
INSERT INTO SymptomNames (sName) VALUES ('apnea');
INSERT INTO SymptomNames (sName) VALUES ('steatorrhea');
INSERT INTO SymptomNames (sName) VALUES ('apraxia');
INSERT INTO SymptomNames (sName) VALUES ('tinnitus');
INSERT INTO SymptomNames (sName) VALUES ('dysarthria');
INSERT INTO SymptomNames (sName) VALUES ('agraphia');
INSERT INTO SymptomNames (sName) VALUES ('dystonia');
INSERT INTO SymptomNames (sName) VALUES ('akinesia');
INSERT INTO SymptomNames (sName) VALUES ('alexia');
INSERT INTO SymptomNames (sName) VALUES ('chorea');
INSERT INTO SymptomNames (sName) VALUES ('loss of appetite');
INSERT INTO SymptomNames (sName) VALUES ('diarrhea');
INSERT INTO SymptomNames (sName) VALUES ('abdominal distension');
INSERT INTO SymptomNames (sName) VALUES ('weight loss');
INSERT INTO SymptomNames (sName) VALUES ('melena');
INSERT INTO SymptomNames (sName) VALUES ('hematochesia');
INSERT INTO SymptomNames (sName) VALUES ('bloating');
INSERT INTO SymptomNames (sName) VALUES ('indigestion');
INSERT INTO SymptomNames (sName) VALUES ('jaundice');
INSERT INTO SymptomNames (sName) VALUES ('light colored stools');
INSERT INTO SymptomNames (sName) VALUES ('dark urine');
INSERT INTO SymptomNames (sName) VALUES ('shortness of breath');
INSERT INTO SymptomNames (sName) VALUES ('lightheadedness');
INSERT INTO SymptomNames (sName) VALUES ('constipation');

INSERT INTO PainPosition (ppName) VALUES ('head');
INSERT INTO PainPosition (ppName) VALUES ('temporal');
INSERT INTO PainPosition (ppName) VALUES ('occipital');
INSERT INTO PainPosition (ppName) VALUES ('frontal');
INSERT INTO PainPosition (ppName) VALUES ('neck');
INSERT INTO PainPosition (ppName) VALUES ('maxilar_sinuses');
INSERT INTO PainPosition (ppName) VALUES ('frontal_sinuses');
INSERT INTO PainPosition (ppName) VALUES ('throat');
INSERT INTO PainPosition (ppName) VALUES ('right_ear');
INSERT INTO PainPosition (ppName) VALUES ('left_ear');
INSERT INTO PainPosition (ppName) VALUES ('jaw');
INSERT INTO PainPosition (ppName) VALUES ('chest');
INSERT INTO PainPosition (ppName) VALUES ('right_chest');
INSERT INTO PainPosition (ppName) VALUES ('left_chest');
INSERT INTO PainPosition (ppName) VALUES ('right_shoulder');
INSERT INTO PainPosition (ppName) VALUES ('left_shoulder');
INSERT INTO PainPosition (ppName) VALUES ('right_shoulder_blade');
INSERT INTO PainPosition (ppName) VALUES ('left_shoulder_blade');
INSERT INTO PainPosition (ppName) VALUES ('between_shoulder_blades');
INSERT INTO PainPosition (ppName) VALUES ('right_arm');
INSERT INTO PainPosition (ppName) VALUES ('left_arm');
INSERT INTO PainPosition (ppName) VALUES ('abdomen');
INSERT INTO PainPosition (ppName) VALUES ('epigastrium');
INSERT INTO PainPosition (ppName) VALUES ('periumbilical');
INSERT INTO PainPosition (ppName) VALUES ('right_upper_quadrant');
INSERT INTO PainPosition (ppName) VALUES ('left_upper_quadrant');
INSERT INTO PainPosition (ppName) VALUES ('right_lower_quadrant');
INSERT INTO PainPosition (ppName) VALUES ('left_lower_quadrant');
INSERT INTO PainPosition (ppName) VALUES ('right_flank');
INSERT INTO PainPosition (ppName) VALUES ('left_flank');
INSERT INTO PainPosition (ppName) VALUES ('suprapubic');
INSERT INTO PainPosition (ppName) VALUES ('upper_back');
INSERT INTO PainPosition (ppName) VALUES ('lower_back');
INSERT INTO PainPosition (ppName) VALUES ('right_costovertebral');
INSERT INTO PainPosition (ppName) VALUES ('left_costovertebral');
INSERT INTO PainPosition (ppName) VALUES ('pelvic');
INSERT INTO PainPosition (ppName) VALUES ('right_groin');
INSERT INTO PainPosition (ppName) VALUES ('left_groin');
INSERT INTO PainPosition (ppName) VALUES ('right_buttock');
INSERT INTO PainPosition (ppName) VALUES ('left_buttock');
INSERT INTO PainPosition (ppName) VALUES ('anal');
INSERT INTO PainPosition (ppName) VALUES ('testicular');
INSERT INTO PainPosition (ppName) VALUES ('vaginal');
INSERT INTO PainPosition (ppName) VALUES ('right_thigh');
INSERT INTO PainPosition (ppName) VALUES ('left_thigh');
INSERT INTO PainPosition (ppName) VALUES ('right_knee');
INSERT INTO PainPosition (ppName) VALUES ('left_knee');
INSERT INTO PainPosition (ppName) VALUES ('right_kalf');
INSERT INTO PainPosition (ppName) VALUES ('left_kalf');
INSERT INTO PainPosition (ppName) VALUES ('right_foot');
INSERT INTO PainPosition (ppName) VALUES ('left_foot');

INSERT INTO PainSx (psName) VALUES ('sharp');
INSERT INTO PainSx (psName) VALUES ('dull');
INSERT INTO PainSx (psName) VALUES ('burning');
INSERT INTO PainSx (psName) VALUES ('clenching');
INSERT INTO PainSx (psName) VALUES ('pleuritic');
INSERT INTO PainSx (psName) VALUES ('colicky');
INSERT INTO PainSx (psName) VALUES ('constant');
INSERT INTO PainSx (psName) VALUES ('on_rest');
INSERT INTO PainSx (psName) VALUES ('on_exertion');
INSERT INTO PainSx (psName) VALUES ('dysuria');
INSERT INTO PainSx (psName) VALUES ('dysparenunia');
INSERT INTO PainSx (psName) VALUES ('four_hours');
INSERT INTO PainSx (psName) VALUES ('eight_hours');
INSERT INTO PainSx (psName) VALUES ('one_day');
INSERT INTO PainSx (psName) VALUES ('two_days');
INSERT INTO PainSx (psName) VALUES ('one_week');
INSERT INTO PainSx (psName) VALUES ('one_month');
INSERT INTO PainSx (psName) VALUES ('six_months');
INSERT INTO PainSx (psName) VALUES ('better_with_rest');
INSERT INTO PainSx (psName) VALUES ('better_with_lying_still');
INSERT INTO PainSx (psName) VALUES ('better_with_moving_around');
INSERT INTO PainSx (psName) VALUES ('worse_with_breathing');
INSERT INTO PainSx (psName) VALUES ('worse_with_eating');
INSERT INTO PainSx (psName) VALUES ('worse_with_moving_around');
INSERT INTO PainSx (psName) VALUES ('worse_with_bending_forward');

INSERT INTO Positions VALUES (0);
INSERT INTO Symptoms VALUES (0);
INSERT INTO Pain VALUES (0, 0, 0);

ALTER SEQUENCE positions_posid_seq RESTART WITH 10000;
ALTER SEQUENCE symptoms_sxid_seq RESTART WITH 10000;
ALTER SEQUENCE cases_caseid_seq RESTART WITH 10000;
ALTER SEQUENCE pain_pid_seq RESTART WITH 10000;
ALTER SEQUENCE diagnosis_did_seq RESTART WITH 10000;
