INSERT INTO SymptomNames (sName) VALUES ('palpitations');
INSERT INTO SymptomNames (sName) VALUES ('chills');
INSERT INTO SymptomNames (sName) VALUES ('clammy skin');
INSERT INTO SymptomNames (sName) VALUES ('cloudy urine');
INSERT INTO SymptomNames (sName) VALUES ('cold sweat');
INSERT INTO SymptomNames (sName) VALUES ('conjunctivitis');
INSERT INTO SymptomNames (sName) VALUES ('cough');
INSERT INTO SymptomNames (sName) VALUES ('dry cough');
INSERT INTO SymptomNames (sName) VALUES ('productive cough');
INSERT INTO SymptomNames (sName) VALUES ('hemoptysis');
INSERT INTO SymptomNames (sName) VALUES ('dehydration');
INSERT INTO SymptomNames (sName) VALUES ('dizziness');
INSERT INTO SymptomNames (sName) VALUES ('dysuria');
INSERT INTO SymptomNames (sName) VALUES ('tachypnea');
INSERT INTO SymptomNames (sName) VALUES ('fatigue');
INSERT INTO SymptomNames (sName) VALUES ('fever');
INSERT INTO SymptomNames (sName) VALUES ('hematuria');
INSERT INTO SymptomNames (sName) VALUES ('hypotension');
INSERT INTO SymptomNames (sName) VALUES ('dyspepsia');
INSERT INTO SymptomNames (sName) VALUES ('presyncope');
INSERT INTO SymptomNames (sName) VALUES ('syncope');
INSERT INTO SymptomNames (sName) VALUES ('malaise');
INSERT INTO SymptomNames (sName) VALUES ('rhinitis');
INSERT INTO SymptomNames (sName) VALUES ('nausea');
INSERT INTO SymptomNames (sName) VALUES ('rhinorrhea');
INSERT INTO SymptomNames (sName) VALUES ('sense of incomplete bladder emptying');
INSERT INTO SymptomNames (sName) VALUES ('dyspnea');
INSERT INTO SymptomNames (sName) VALUES ('smelly urine');
INSERT INTO SymptomNames (sName) VALUES ('sneezing');
INSERT INTO SymptomNames (sName) VALUES ('diaphoresis');
INSERT INTO SymptomNames (sName) VALUES ('tachycardia');
INSERT INTO SymptomNames (sName) VALUES ('polyuria');
INSERT INTO SymptomNames (sName) VALUES ('vomiting');
INSERT INTO SymptomNames (sName) VALUES ('dysphagia');
INSERT INTO SymptomNames (sName) VALUES ('ataxia');
INSERT INTO SymptomNames (sName) VALUES ('bradykinesia');
INSERT INTO SymptomNames (sName) VALUES ('impotence');
INSERT INTO SymptomNames (sName) VALUES ('bradypnea');
INSERT INTO SymptomNames (sName) VALUES ('apnea');
INSERT INTO SymptomNames (sName) VALUES ('steatorrhea');
INSERT INTO SymptomNames (sName) VALUES ('apraxia');
INSERT INTO SymptomNames (sName) VALUES ('tinnitus');
INSERT INTO SymptomNames (sName) VALUES ('dysarthria');
INSERT INTO SymptomNames (sName) VALUES ('dysgraphia');
INSERT INTO SymptomNames (sName) VALUES ('dystonia');
INSERT INTO SymptomNames (sName) VALUES ('akinesia');
INSERT INTO SymptomNames (sName) VALUES ('alexia');
INSERT INTO SymptomNames (sName) VALUES ('chorea');
INSERT INTO SymptomNames (sName) VALUES ('loss of appetite');
INSERT INTO SymptomNames (sName) VALUES ('diarrhea');
INSERT INTO SymptomNames (sName) VALUES ('abdominal distension');
INSERT INTO SymptomNames (sName) VALUES ('weight loss');
INSERT INTO SymptomNames (sName) VALUES ('melena');
INSERT INTO SymptomNames (sName) VALUES ('hematochesia');
INSERT INTO SymptomNames (sName) VALUES ('bloating');
INSERT INTO SymptomNames (sName) VALUES ('indigestion');
INSERT INTO SymptomNames (sName) VALUES ('jaundice');
INSERT INTO SymptomNames (sName) VALUES ('light colored stools');
INSERT INTO SymptomNames (sName) VALUES ('dark urine');
INSERT INTO SymptomNames (sName) VALUES ('shortness of breath');
INSERT INTO SymptomNames (sName) VALUES ('lightheadedness');
INSERT INTO SymptomNames (sName) VALUES ('constipation');